name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: test
        with:
          file: ./test/test.yaml
      - run: |
          echo ${{ steps.test.outputs.version }}
          echo ${{ steps.test.outputs.staging_release }}
          echo ${{ steps.test.outputs.staging_namespace }}
          echo ${{ steps.test.outputs.production_release }}
          echo ${{ steps.test.outputs.production_namespace }}
